version: '3.8'

services:
  app:
    build: .
    container_name: hr-system-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LHDN_API_KEY=${LHDN_API_KEY}
      - KWSP_API_KEY=${KWSP_API_KEY}
      - PERKESO_API_KEY=${PERKESO_API_KEY}
      - HRDF_API_KEY=${HRDF_API_KEY}
      - MYWORKID_API_KEY=${MYWORKID_API_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT}
      - SENTRY_DSN=${SENTRY_DSN}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_PROMETHEUS=${ENABLE_PROMETHEUS}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
      - BACKUP_PATH=${BACKUP_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CA_PATH=${SSL_CA_PATH}
      - LOAD_BALANCER_TYPE=${LOAD_BALANCER_TYPE}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL}
      - HEALTH_CHECK_TIMEOUT=${HEALTH_CHECK_TIMEOUT}
      - MIN_INSTANCES=${MIN_INSTANCES}
      - MAX_INSTANCES=${MAX_INSTANCES}
      - CPU_THRESHOLD=${CPU_THRESHOLD}
      - MEMORY_THRESHOLD=${MEMORY_THRESHOLD}
      - ENABLE_AI_AGENTS=${ENABLE_AI_AGENTS}
      - ENABLE_GOVERNMENT_INTEGRATION=${ENABLE_GOVERNMENT_INTEGRATION}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS}
      - ENABLE_NOTIFICATIONS=${ENABLE_NOTIFICATIONS}
      - ENABLE_BACKUP=${ENABLE_BACKUP}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - CACHE_TTL=${CACHE_TTL}
      - DB_CONNECTION_POOL_SIZE=${DB_CONNECTION_POOL_SIZE}
      - API_TIMEOUT=${API_TIMEOUT}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./ssl:/app/ssl
      - ./logs:/app/logs
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    container_name: hr-system-redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:15-alpine
    container_name: hr-system-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-data:
  pgdata:
